version: '3'
services: 
  web:
    tty: true
    build: ./web
    ports: 
      - "80:80"
    volumes: 
      - ./backend/code/sample/static:/static
    depends_on:
      - backend
    container_name: web
  frontend:
    tty: true
    build: ./frontend
    container_name: frontend
    ports: 
      - "3000:3000"
    volumes: 
      - ./frontend/code:/code
    depends_on:
      - backend
  backend:
    tty: true
    build: ./backend
    ports: 
      - "8000:8000"
      - "5678:5678"
    volumes: 
      - ./backend/code:/code
    depends_on:
      - db
    container_name: backend
  db:
    tty: true
    build: ./db
    environment:
      MYSQL_ROOT_PASSWORD: django
      MYSQL_DATABASE: django
      MYSQL_USER: django
      MYSQL_PASSWORD: django    
    ports: 
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./db/mysql_data:/var/lib/mysql
    container_name: db